spring:
  config:
    activate:
      on-profile: localConsumer
  kafka:
    consumer:
      bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
      properties:
        spring.json.trusted.packages: team.bakkas.*