pipeline {
    agent any

    environment {
        ECR_REPO = "326991552997.dkr.ecr.ap-northeast-2.amazonaws.com/withmarket-shop-search"
        AWS_CREDENTIALS = "jenkins_deploy_user_credentials"
        NAME = "shop-search"
    }

    stages {
        stage("Build functions module") {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'chmod 755 ./gradlew'
                    sh './gradlew build'
                }
            }

            post {
                success {
                    echo 'The Build stage is done successfully.'
                }

                failure {
                    echo 'The Build stage is fail.'
                }
            }
        }

        stage("Build docker image") {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'docker build -t ${NAME} .'
                    sh 'docker tag ${NAME}:latest ${ECR_REPO}:latest'
                }
            }

            post {
                success {
                    echo 'The docker build is done successfully.'
                }

                failure {
                    echo 'The docker build is failed.'
                }
            }
        }

        stage("ECR Upload") {
            steps {
                script {
                    try {
                        withAWS(credentials: "${AWS_CREDENTIALS}", role: 'arn:aws:iam::326991552997:role/jenkins_deploy_role', roleAccount: "326991552997", externalId: "18k7102dy@gmail.com") {
                            sh "aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${ECR_REPO}"
                            sh 'docker push ${ECR_REPO}:latest'
                        }
                    }catch(error) {
                        print(error)
                        currentBuild.result = 'FAILURE'
                    }
                }
            }

            post {
                success {
                    echo "The ECR Upload stage is done successfully."
                }
                failure {
                    echo "The ECR Upload stage is fail."
                }
            }
        }
    }

    post {
        success {
            slackSend(
                channel: "#server-build-history",
                color: "good",
                message: "[Successful] Job:${env.JOB_NAME}, Build num:#${env.BUILD_NUMBER} (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )
        }

        failure {
            slackSend(
                channel: "#server-build-history",
                color: "danger",
                message: "[Failed] Job:${env.JOB_NAME}, Build num:#${env.BUILD_NUMBER} @channel (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )
        }
    }
}