pipeline {
    agent any

    environment {

    }

    stages {
        stage("Build functions module") {

        }

        stage("Push to S3") {

        }

        stage("Fargate Update") {

        }
    }
}